# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 't2g_port_debug_console.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 300)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 260, 681, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.cLabel.setObjectName("cLabel")
        self.horizontalLayout.addWidget(self.cLabel)
        self.inputLine = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.inputLine.setObjectName("inputLine")
        self.horizontalLayout.addWidget(self.inputLine)
        self.sendButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout.addWidget(self.sendButton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 281, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.serialLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serialLabel.sizePolicy().hasHeightForWidth())
        self.serialLabel.setSizePolicy(sizePolicy)
        self.serialLabel.setObjectName("serialLabel")
        self.horizontalLayout_2.addWidget(self.serialLabel)
        self.serialBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.serialBox.setObjectName("serialBox")
        self.horizontalLayout_2.addWidget(self.serialBox)
        self.connectButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setMaximumSize(QtCore.QSize(55, 16777215))
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout_2.addWidget(self.connectButton)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(570, 10, 125, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.baudLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baudLabel.sizePolicy().hasHeightForWidth())
        self.baudLabel.setSizePolicy(sizePolicy)
        self.baudLabel.setObjectName("baudLabel")
        self.horizontalLayout_3.addWidget(self.baudLabel)
        self.baudBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.baudBox.setObjectName("baudBox")
        self.horizontalLayout_3.addWidget(self.baudBox)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 681, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.outLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.outLabel.setObjectName("outLabel")
        self.verticalLayout.addWidget(self.outLabel)
        self.output = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(300, 10, 111, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.testGeoGSIButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.testGeoGSIButton.setObjectName("testGeoGSIButton")
        self.horizontalLayout_4.addWidget(self.testGeoGSIButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "T2G Serial debug console"))
        self.cLabel.setText(_translate("Dialog", "Command:"))
        self.sendButton.setText(_translate("Dialog", "Send"))
        self.serialLabel.setText(_translate("Dialog", "Serial Port:"))
        self.connectButton.setText(_translate("Dialog", "Connect"))
        self.baudLabel.setText(_translate("Dialog", "Baudrate:"))
        self.outLabel.setText(_translate("Dialog", "Output:"))
        self.testGeoGSIButton.setText(_translate("Dialog", "GeoCOM/GSI test"))

